
package team17.sheet09.client.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "RemoteCalculatorService", targetNamespace = "http://server.sheet09.team17/", wsdlLocation = "http://localhost:8080/sheet09/services/Calculator?wsdl")
public class RemoteCalculatorService
        extends Service {

    private final static URL REMOTECALCULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException REMOTECALCULATORSERVICE_EXCEPTION;
    private final static QName REMOTECALCULATORSERVICE_QNAME = new QName("http://server.sheet09.team17/", "RemoteCalculatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sheet09/services/Calculator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REMOTECALCULATORSERVICE_WSDL_LOCATION = url;
        REMOTECALCULATORSERVICE_EXCEPTION = e;
    }

    public RemoteCalculatorService() {
        super(__getWsdlLocation(), REMOTECALCULATORSERVICE_QNAME);
    }

    public RemoteCalculatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REMOTECALCULATORSERVICE_QNAME, features);
    }

    public RemoteCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, REMOTECALCULATORSERVICE_QNAME);
    }

    public RemoteCalculatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REMOTECALCULATORSERVICE_QNAME, features);
    }

    public RemoteCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RemoteCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (REMOTECALCULATORSERVICE_EXCEPTION != null) {
            throw REMOTECALCULATORSERVICE_EXCEPTION;
        }
        return REMOTECALCULATORSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns RemoteCalculator
     */
    @WebEndpoint(name = "RemoteCalculatorPort")
    public RemoteCalculator getRemoteCalculatorPort() {
        return super.getPort(new QName("http://server.sheet09.team17/", "RemoteCalculatorPort"), RemoteCalculator.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns RemoteCalculator
     */
    @WebEndpoint(name = "RemoteCalculatorPort")
    public RemoteCalculator getRemoteCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.sheet09.team17/", "RemoteCalculatorPort"), RemoteCalculator.class, features);
    }

}
