
package team17.sheet09.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "RemoteCalculator", targetNamespace = "http://server.sheet09.team17/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface RemoteCalculator {


    /**
     * @param arg1
     * @param arg0
     * @return returns int
     */
    @WebMethod(operationName = "Add")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Add", targetNamespace = "http://server.sheet09.team17/", className = "team17.sheet09.client.ws.Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://server.sheet09.team17/", className = "team17.sheet09.client.ws.AddResponse")
    @Action(input = "http://server.sheet09.team17/RemoteCalculator/AddRequest", output = "http://server.sheet09.team17/RemoteCalculator/AddResponse")
    int add(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns int
     */
    @WebMethod(operationName = "Multiply")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Multiply", targetNamespace = "http://server.sheet09.team17/", className = "team17.sheet09.client.ws.Multiply")
    @ResponseWrapper(localName = "MultiplyResponse", targetNamespace = "http://server.sheet09.team17/", className = "team17.sheet09.client.ws.MultiplyResponse")
    @Action(input = "http://server.sheet09.team17/RemoteCalculator/MultiplyRequest", output = "http://server.sheet09.team17/RemoteCalculator/MultiplyResponse")
    int multiply(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns int
     */
    @WebMethod(operationName = "Subtract")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Subtract", targetNamespace = "http://server.sheet09.team17/", className = "team17.sheet09.client.ws.Subtract")
    @ResponseWrapper(localName = "SubtractResponse", targetNamespace = "http://server.sheet09.team17/", className = "team17.sheet09.client.ws.SubtractResponse")
    @Action(input = "http://server.sheet09.team17/RemoteCalculator/SubtractRequest", output = "http://server.sheet09.team17/RemoteCalculator/SubtractResponse")
    int subtract(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1);

    /**
     * @param arg0
     * @return returns int
     */
    @WebMethod(operationName = "Lucas")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Lucas", targetNamespace = "http://server.sheet09.team17/", className = "team17.sheet09.client.ws.Lucas")
    @ResponseWrapper(localName = "LucasResponse", targetNamespace = "http://server.sheet09.team17/", className = "team17.sheet09.client.ws.LucasResponse")
    @Action(input = "http://server.sheet09.team17/RemoteCalculator/LucasRequest", output = "http://server.sheet09.team17/RemoteCalculator/LucasResponse")
    int lucas(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

}
